### ISSUE TITLE
Production/Stable Release

### ISSUE THREAD

**Issue by steven-upside** [mattgiles/mujson#1]
I'd like to second the request made by @kgriffs in https://github.com/falconry/falcon/issues/1206#issuecomment-379295321. 

I would love to use this library, but would feel more comfortable with a `1.0` release.

**Comment by mattgiles** [comment]
I have bumped the release to 1.0, with appropriate classification on PYPI, and also added support for PYPY. The benchmarks are standing in for tests right now. Will see about standing up tests and builds in a separate issue.
